### ISSUE TITLE
missing .dll

### ISSUE THREAD

**Issue by odsttroop787** [tracktwo/ppdefmodifier#10]
I don't know if im blind or if im missing something, im sure its on me, but i cant find the .dll for the injector because with modnix it isnt working.

**Comment by tracktwo** [comment]
It's on the releases tab -- https://github.com/tracktwo/ppdefmodifier/releases/tag/1.6

It's not in the most obvious spot unless you're familiar with Github.

**Comment by odsttroop787** [comment]
Thank you I figured it not even 5 min. After sending the issue in. Sorry
for wasting your time I'm still getting used to GitHub

**Comment by tracktwo** [comment]
No problem and you definitely aren't the first person to have this problem. I'll add a link to the main readme.

**Comment by tracktwo** [comment]
Updated the main readme with the link.
