### ISSUE TITLE
Extract "field" when the value is inside a list

### ISSUE THREAD

**Issue by ArmitageJakeTurtle** [tracktwo/ppdefmodifier#2]
Hi, sorry if I bother you
I'm a long time TW modder (Rome 2 DeI) and now I've started checking how to mod Phoenix Point.

I would like to make you a question.

Every facility resource cost has this type of construction (example taken from --> MutationLab_PhoenixFacilityDef)

->
ResourcePack ResourceCost
List`1 Values
int size = 2
[0]
ResourceUnit data
ResourceType Type = 2
Single Value = 250
[1]
ResourceUnit data
ResourceType Type = 4
Single Value = 75
<-

So... if I would like to change the resource cost how I'm gonna identify the complete "field" since I have to overwrite via json the "Single Value"?
Is it even possible?

**Comment by tracktwo** [comment]
It should be possible, you can modify lists like arrays with `[]`. Try something like
```json
"field": "ResourceCost.Values[0].Value",
"value": 200
```

(In this case "Single" is the type, a floating point number, and "Value" is the name of the field you want to change).

**Comment by JJ2197** [comment]
Although this seems like it should work as it has a similar structure to the DamagePayload.DamageKeywords array, but for some reason it doesn't work.

**Comment by ArmitageJakeTurtle** [comment]
yep. both me and JJ already tried that.
I've tried also "less logical" insertion but nothing, till now at least.

Sadly my real "coding" knowledge is pratically 0 (just some regarding lua coming from modding Rome2), so my only solution is to do trials hoping that the actual issue is solvable.

Speaking about my coding ignorance, would doing something with loops solve anything?
Or I'm just suggesting an heresy?

Dunno, something like: https://www.w3schools.com/js/js_json_arrays.asp

**Comment by tracktwo** [comment]
Looks like something has changed internally with these resource packs with the last patch. I don't have the old DLL to compare, but another local change that I had been testing also broke with this patch. Either that or it never worked and I didn't notice :)

I've made a fix and uploaded v1.3 that should fix this with the syntax in my original response above.

**Comment by ArmitageJakeTurtle** [comment]
and...
YES!

problem solved.
Thanks a lot man!

**Comment by ArmitageJakeTurtle** [comment]
btw, I would really like to thank you for you work, I'm enjoying while trying to build something for an hypothetical mod. 
Thanks for giving me the possibility

**Comment by tracktwo** [comment]
Glad it's useful!
