### ISSUE TITLE
Modifying Ability availability.. if possible.

### ISSUE THREAD

**Issue by jarnomikkola1** [tracktwo/ppdefmodifier#5]
As you probably know, the Customized Game Tweak mod at the Phoenix Point Nexus has the ability chart pasted to pastebin here: https://pastebin.com/eETXbkmq
It has intresting values I would like to be able to modify if it does what it says in the thin, this: 
"Boolean AvailableToHumanPlayer = True" .. of course it might not do what it says and finding that out would result in no real difference, but my hope is that for example one could disable the Cautious ability from the available character selection, so it would then randomize one of the other 13 abilities to the character. 
I tried this first of course with: 
{
"guid": "ae8bc7e4-ff06-0da4-8862-5379229272f5",
"field": "AvailableToHumanPlayer",
"value": False,
"comment": "removes Cautious"
}
But was unsuccessful, so .. can this be done, and if not, can you make it possible ? And if I failed to code it correctly, can you help to code it, so it is correct ? 

Thanks in advance.

**Comment by tracktwo** [comment]
That mod was last updated on January 19, I think it's out of date with later patches and DLC. I've also heard from others that some of the patches listed there don't work anymore.

I took a quick look at the asset file in asset studio as of the current patch + Blood and Titanium, and there is no 'AvailableToHumanPlayer' field in the ability def at all (AvailableToAI is gone too). I double-checked in the DLL and there is no reference to that field. I don't have a backup copy of the old version to see what it used to do, but whatever it was it looks like it's been removed.

If there is no longer any field in the def that controls this then PPDefModifier won't be able to make such a change, it'd need to be made as a full .DLL mod.

**Comment by jarnomikkola1** [comment]
Hmm, alright, closing the issue.
