### ISSUE TITLE
Possible to alter the color values? Not sure about the syntax...

### ISSUE THREAD

**Issue by jvarnes** [tracktwo/ppdefmodifier#6]
Hi. Thanks so much for writing PPdef. It's a great tool and I'm having a lot of fun modding my game to see what I can change and improve. Looking to release a large overhaul mod when I'm done.

My question / issue is with a specific entry for color palettes. How would you (could you) write a change entry like damage payload (i.e. DamagePayload.DamageKeywords[0].Value) for this entry (taken from CustomizationColorPaletteDef):

List`1 ArmorColorsPalette
	int size = 15
		[0]
		TagsToColorSettings data
			PPtr<CustomizationPrimaryColorTagDef> tag = {fileID: 0, pathID: 214567}
			PPtr<CustomizationSecondaryColorTagDef> alternativeTag = {fileID: 0, pathID: 214598}
			Color matchedColor
				Single r = 0.5019608
				Single g = 0.5019608
				Single b = 0.5019608
				Single a = 1

I tried ArmorColorsPalette.matchedColor[0].r but that's clearly not the correct syntax...

I'm not sure it CAN be done since the nesting seems a bit different...

Any ideas?

Thanks so much!

**Comment by tracktwo** [comment]
Hi,

Almost right - `ArmorColorsPalette` is the list, not `matchedColor`, so the syntax should be:

`ArmorColorsPalette[0].matchedColor.r` (etc).

Here's a block I tested that sets the 1st armor customization colour to pure red (it actually shows up a little pink in-game, the colours don't match exactly):

```
{
        "guid": "8de0c1e9-a630-c5f4-887c-405ed2f69e67",
        "field": "ArmorColorsPalette[0].matchedColor.r",
        "value": 1.0,
        "comment": "armor 0 red"
},
{
        "guid": "8de0c1e9-a630-c5f4-887c-405ed2f69e67",
        "field": "ArmorColorsPalette[0].matchedColor.g",
        "value": 0,
        "comment": "armor 0 green"
},
{
        "guid": "8de0c1e9-a630-c5f4-887c-405ed2f69e67",
        "field": "ArmorColorsPalette[0].matchedColor.b",
        "value": 0,
        "comment": "armor 0 blue"
}
```

**Comment by jvarnes** [comment]
Awesome! Thanks for the help :)
